app:
  language: tr
  store:
    customer-list:
    - height: 200
      name: osman
      surname: yay
      weight: 95
    - height: 180
      name: ali
      surname: veli
      weight: 110
    customer-map:
      osmanyay:
        height: 190
        name: osman
        surname: ulak
        weight: 98
    desc: training
    language: tr
    location: istanbul
    sub-properties:
      prop1: test1
      prop2: test2
    version: 1.0.0
server:
  http2:
    enabled: false
  port: 9090
